
networks:
  movie-streams:
    name: movie-streams
    external: true


services:
  movie-service:
    container_name: movie-service
    build: ./movie-service
    mem_limit: "500mb"
    cpus: 0.5
    ports:
      - 8200:8200
    networks:
      - movie-streams



  movie-search:
    container_name: movie-search
    build: movie-elasticsearch
    mem_limit: "200mb"
    cpus: 0.3
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports:
      - 8080:8080
    networks:
      - movie-streams

