/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafkastreams.movie.commons.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MovieVideoJoined extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5716454664159068815L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MovieVideoJoined\",\"namespace\":\"com.kafkastreams.movie.commons.avro\",\"fields\":[{\"name\":\"videoUrl\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"movieId\",\"type\":\"int\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"genre\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"synopsis\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"releaseYear\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"image\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rating\",\"type\":\"float\"},{\"name\":\"director\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"cast\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<MovieVideoJoined> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MovieVideoJoined> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MovieVideoJoined> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MovieVideoJoined> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MovieVideoJoined> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MovieVideoJoined to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MovieVideoJoined from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MovieVideoJoined instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MovieVideoJoined fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String videoUrl;
  private int movieId;
  private java.lang.String name;
  private java.util.List<java.lang.String> genre;
  private java.lang.String synopsis;
  private java.time.Instant releaseYear;
  private java.lang.String image;
  private float rating;
  private java.util.List<java.lang.String> director;
  private java.util.List<java.lang.String> cast;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MovieVideoJoined() {}

  /**
   * All-args constructor.
   * @param videoUrl The new value for videoUrl
   * @param movieId The new value for movieId
   * @param name The new value for name
   * @param genre The new value for genre
   * @param synopsis The new value for synopsis
   * @param releaseYear The new value for releaseYear
   * @param image The new value for image
   * @param rating The new value for rating
   * @param director The new value for director
   * @param cast The new value for cast
   */
  public MovieVideoJoined(java.lang.String videoUrl, java.lang.Integer movieId, java.lang.String name, java.util.List<java.lang.String> genre, java.lang.String synopsis, java.time.Instant releaseYear, java.lang.String image, java.lang.Float rating, java.util.List<java.lang.String> director, java.util.List<java.lang.String> cast) {
    this.videoUrl = videoUrl;
    this.movieId = movieId;
    this.name = name;
    this.genre = genre;
    this.synopsis = synopsis;
    this.releaseYear = releaseYear.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.image = image;
    this.rating = rating;
    this.director = director;
    this.cast = cast;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return videoUrl;
    case 1: return movieId;
    case 2: return name;
    case 3: return genre;
    case 4: return synopsis;
    case 5: return releaseYear;
    case 6: return image;
    case 7: return rating;
    case 8: return director;
    case 9: return cast;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: videoUrl = value$ != null ? value$.toString() : null; break;
    case 1: movieId = (java.lang.Integer)value$; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: genre = (java.util.List<java.lang.String>)value$; break;
    case 4: synopsis = value$ != null ? value$.toString() : null; break;
    case 5: releaseYear = (java.time.Instant)value$; break;
    case 6: image = value$ != null ? value$.toString() : null; break;
    case 7: rating = (java.lang.Float)value$; break;
    case 8: director = (java.util.List<java.lang.String>)value$; break;
    case 9: cast = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'videoUrl' field.
   * @return The value of the 'videoUrl' field.
   */
  public java.lang.String getVideoUrl() {
    return videoUrl;
  }


  /**
   * Sets the value of the 'videoUrl' field.
   * @param value the value to set.
   */
  public void setVideoUrl(java.lang.String value) {
    this.videoUrl = value;
  }

  /**
   * Gets the value of the 'movieId' field.
   * @return The value of the 'movieId' field.
   */
  public int getMovieId() {
    return movieId;
  }


  /**
   * Sets the value of the 'movieId' field.
   * @param value the value to set.
   */
  public void setMovieId(int value) {
    this.movieId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'genre' field.
   * @return The value of the 'genre' field.
   */
  public java.util.List<java.lang.String> getGenre() {
    return genre;
  }


  /**
   * Sets the value of the 'genre' field.
   * @param value the value to set.
   */
  public void setGenre(java.util.List<java.lang.String> value) {
    this.genre = value;
  }

  /**
   * Gets the value of the 'synopsis' field.
   * @return The value of the 'synopsis' field.
   */
  public java.lang.String getSynopsis() {
    return synopsis;
  }


  /**
   * Sets the value of the 'synopsis' field.
   * @param value the value to set.
   */
  public void setSynopsis(java.lang.String value) {
    this.synopsis = value;
  }

  /**
   * Gets the value of the 'releaseYear' field.
   * @return The value of the 'releaseYear' field.
   */
  public java.time.Instant getReleaseYear() {
    return releaseYear;
  }


  /**
   * Sets the value of the 'releaseYear' field.
   * @param value the value to set.
   */
  public void setReleaseYear(java.time.Instant value) {
    this.releaseYear = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'image' field.
   * @return The value of the 'image' field.
   */
  public java.lang.String getImage() {
    return image;
  }


  /**
   * Sets the value of the 'image' field.
   * @param value the value to set.
   */
  public void setImage(java.lang.String value) {
    this.image = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public float getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(float value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'director' field.
   * @return The value of the 'director' field.
   */
  public java.util.List<java.lang.String> getDirector() {
    return director;
  }


  /**
   * Sets the value of the 'director' field.
   * @param value the value to set.
   */
  public void setDirector(java.util.List<java.lang.String> value) {
    this.director = value;
  }

  /**
   * Gets the value of the 'cast' field.
   * @return The value of the 'cast' field.
   */
  public java.util.List<java.lang.String> getCast() {
    return cast;
  }


  /**
   * Sets the value of the 'cast' field.
   * @param value the value to set.
   */
  public void setCast(java.util.List<java.lang.String> value) {
    this.cast = value;
  }

  /**
   * Creates a new MovieVideoJoined RecordBuilder.
   * @return A new MovieVideoJoined RecordBuilder
   */
  public static com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder newBuilder() {
    return new com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder();
  }

  /**
   * Creates a new MovieVideoJoined RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MovieVideoJoined RecordBuilder
   */
  public static com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder newBuilder(com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder other) {
    if (other == null) {
      return new com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder();
    } else {
      return new com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder(other);
    }
  }

  /**
   * Creates a new MovieVideoJoined RecordBuilder by copying an existing MovieVideoJoined instance.
   * @param other The existing instance to copy.
   * @return A new MovieVideoJoined RecordBuilder
   */
  public static com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder newBuilder(com.kafkastreams.movie.commons.avro.MovieVideoJoined other) {
    if (other == null) {
      return new com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder();
    } else {
      return new com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder(other);
    }
  }

  /**
   * RecordBuilder for MovieVideoJoined instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MovieVideoJoined>
    implements org.apache.avro.data.RecordBuilder<MovieVideoJoined> {

    private java.lang.String videoUrl;
    private int movieId;
    private java.lang.String name;
    private java.util.List<java.lang.String> genre;
    private java.lang.String synopsis;
    private java.time.Instant releaseYear;
    private java.lang.String image;
    private float rating;
    private java.util.List<java.lang.String> director;
    private java.util.List<java.lang.String> cast;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.videoUrl)) {
        this.videoUrl = data().deepCopy(fields()[0].schema(), other.videoUrl);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.movieId)) {
        this.movieId = data().deepCopy(fields()[1].schema(), other.movieId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.genre)) {
        this.genre = data().deepCopy(fields()[3].schema(), other.genre);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.synopsis)) {
        this.synopsis = data().deepCopy(fields()[4].schema(), other.synopsis);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.releaseYear)) {
        this.releaseYear = data().deepCopy(fields()[5].schema(), other.releaseYear);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.image)) {
        this.image = data().deepCopy(fields()[6].schema(), other.image);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.rating)) {
        this.rating = data().deepCopy(fields()[7].schema(), other.rating);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.director)) {
        this.director = data().deepCopy(fields()[8].schema(), other.director);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.cast)) {
        this.cast = data().deepCopy(fields()[9].schema(), other.cast);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing MovieVideoJoined instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafkastreams.movie.commons.avro.MovieVideoJoined other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.videoUrl)) {
        this.videoUrl = data().deepCopy(fields()[0].schema(), other.videoUrl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.movieId)) {
        this.movieId = data().deepCopy(fields()[1].schema(), other.movieId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.genre)) {
        this.genre = data().deepCopy(fields()[3].schema(), other.genre);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.synopsis)) {
        this.synopsis = data().deepCopy(fields()[4].schema(), other.synopsis);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.releaseYear)) {
        this.releaseYear = data().deepCopy(fields()[5].schema(), other.releaseYear);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.image)) {
        this.image = data().deepCopy(fields()[6].schema(), other.image);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.rating)) {
        this.rating = data().deepCopy(fields()[7].schema(), other.rating);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.director)) {
        this.director = data().deepCopy(fields()[8].schema(), other.director);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.cast)) {
        this.cast = data().deepCopy(fields()[9].schema(), other.cast);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'videoUrl' field.
      * @return The value.
      */
    public java.lang.String getVideoUrl() {
      return videoUrl;
    }


    /**
      * Sets the value of the 'videoUrl' field.
      * @param value The value of 'videoUrl'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setVideoUrl(java.lang.String value) {
      validate(fields()[0], value);
      this.videoUrl = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'videoUrl' field has been set.
      * @return True if the 'videoUrl' field has been set, false otherwise.
      */
    public boolean hasVideoUrl() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'videoUrl' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearVideoUrl() {
      videoUrl = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'movieId' field.
      * @return The value.
      */
    public int getMovieId() {
      return movieId;
    }


    /**
      * Sets the value of the 'movieId' field.
      * @param value The value of 'movieId'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setMovieId(int value) {
      validate(fields()[1], value);
      this.movieId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'movieId' field has been set.
      * @return True if the 'movieId' field has been set, false otherwise.
      */
    public boolean hasMovieId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'movieId' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearMovieId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getGenre() {
      return genre;
    }


    /**
      * Sets the value of the 'genre' field.
      * @param value The value of 'genre'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setGenre(java.util.List<java.lang.String> value) {
      validate(fields()[3], value);
      this.genre = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'genre' field has been set.
      * @return True if the 'genre' field has been set, false otherwise.
      */
    public boolean hasGenre() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'genre' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearGenre() {
      genre = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'synopsis' field.
      * @return The value.
      */
    public java.lang.String getSynopsis() {
      return synopsis;
    }


    /**
      * Sets the value of the 'synopsis' field.
      * @param value The value of 'synopsis'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setSynopsis(java.lang.String value) {
      validate(fields()[4], value);
      this.synopsis = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'synopsis' field has been set.
      * @return True if the 'synopsis' field has been set, false otherwise.
      */
    public boolean hasSynopsis() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'synopsis' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearSynopsis() {
      synopsis = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'releaseYear' field.
      * @return The value.
      */
    public java.time.Instant getReleaseYear() {
      return releaseYear;
    }


    /**
      * Sets the value of the 'releaseYear' field.
      * @param value The value of 'releaseYear'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setReleaseYear(java.time.Instant value) {
      validate(fields()[5], value);
      this.releaseYear = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'releaseYear' field has been set.
      * @return True if the 'releaseYear' field has been set, false otherwise.
      */
    public boolean hasReleaseYear() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'releaseYear' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearReleaseYear() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'image' field.
      * @return The value.
      */
    public java.lang.String getImage() {
      return image;
    }


    /**
      * Sets the value of the 'image' field.
      * @param value The value of 'image'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setImage(java.lang.String value) {
      validate(fields()[6], value);
      this.image = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'image' field has been set.
      * @return True if the 'image' field has been set, false otherwise.
      */
    public boolean hasImage() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'image' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearImage() {
      image = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public float getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setRating(float value) {
      validate(fields()[7], value);
      this.rating = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearRating() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'director' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getDirector() {
      return director;
    }


    /**
      * Sets the value of the 'director' field.
      * @param value The value of 'director'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setDirector(java.util.List<java.lang.String> value) {
      validate(fields()[8], value);
      this.director = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'director' field has been set.
      * @return True if the 'director' field has been set, false otherwise.
      */
    public boolean hasDirector() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'director' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearDirector() {
      director = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'cast' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getCast() {
      return cast;
    }


    /**
      * Sets the value of the 'cast' field.
      * @param value The value of 'cast'.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder setCast(java.util.List<java.lang.String> value) {
      validate(fields()[9], value);
      this.cast = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'cast' field has been set.
      * @return True if the 'cast' field has been set, false otherwise.
      */
    public boolean hasCast() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'cast' field.
      * @return This builder.
      */
    public com.kafkastreams.movie.commons.avro.MovieVideoJoined.Builder clearCast() {
      cast = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MovieVideoJoined build() {
      try {
        MovieVideoJoined record = new MovieVideoJoined();
        record.videoUrl = fieldSetFlags()[0] ? this.videoUrl : (java.lang.String) defaultValue(fields()[0]);
        record.movieId = fieldSetFlags()[1] ? this.movieId : (java.lang.Integer) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.genre = fieldSetFlags()[3] ? this.genre : (java.util.List<java.lang.String>) defaultValue(fields()[3]);
        record.synopsis = fieldSetFlags()[4] ? this.synopsis : (java.lang.String) defaultValue(fields()[4]);
        record.releaseYear = fieldSetFlags()[5] ? this.releaseYear : (java.time.Instant) defaultValue(fields()[5]);
        record.image = fieldSetFlags()[6] ? this.image : (java.lang.String) defaultValue(fields()[6]);
        record.rating = fieldSetFlags()[7] ? this.rating : (java.lang.Float) defaultValue(fields()[7]);
        record.director = fieldSetFlags()[8] ? this.director : (java.util.List<java.lang.String>) defaultValue(fields()[8]);
        record.cast = fieldSetFlags()[9] ? this.cast : (java.util.List<java.lang.String>) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MovieVideoJoined>
    WRITER$ = (org.apache.avro.io.DatumWriter<MovieVideoJoined>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MovieVideoJoined>
    READER$ = (org.apache.avro.io.DatumReader<MovieVideoJoined>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










