---
version: '3'
networks:
  net:
    name: net
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.1.0/24
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: zookeeper
    networks:
      - net
    ports:
      - "2181:2181"
    volumes:
      - "./data/zookeeper_data:/bitnami"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: docker.io/bitnami/kafka:3
    #    image: debezium/kafka:latest
    container_name: kafka
    restart: unless-stopped
    networks:
      - net
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      #      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"

    depends_on:
      - zookeeper



  kafka-connect:
    image: debezium/connect:latest
    container_name: kafka-connect
    restart: unless-stopped
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
    networks:
      - net
    depends_on:
      - kafka

  mysql:
   image: quay.io/debezium/example-mysql:2.3
   container_name: mysql
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: debezium
     MYSQL_USER: mysqluser
     MYSQL_PASSWORD: mysqlpw
   networks:
     - net

#  mysqlterm:
#    image: mysql:8.0
#    links:
#      - mysql
#    command:
#      - sh -c 'exec mysql -h"mysql" -P"3306" -uroot -p"mysqlpw"'


