spring:
  application:
    name: movies-kafka-streams
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
schemaRegistry: localhost:8081

kafkaServer: localhost:29092

---
spring:
  config:
    activate:
      on-profile: docker

schemaRegistry: schema-registry:8081

kafka:
  bootstrap:
    server: kafka:9092
